# Generated by Django 4.2 on 2023-05-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена за покупку'),
        ),
    ]
