# Generated by Django 4.2 on 2023-05-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_description_alter_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, max_length=50, null=True, verbose_name='slug')),
                ('content', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Содержание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='media/image/', verbose_name='Изображение')),
                ('creation_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('publication_feature', models.CharField(max_length=50, verbose_name='Признак публикации')),
                ('views_count', models.IntegerField(verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блог',
                'ordering': ('views_count',),
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='product',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to='media/image/', verbose_name='Изображение'),
        ),
    ]
