# Generated by Django 4.2 on 2023-05-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_blog_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='creation_date',
            new_name='creation_date_blog',
        ),
    ]
