# Generated by Django 4.2 on 2023-05-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_creation_date_blog_creation_date_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publication_feature',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Признак публикации'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='views_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='количество просмотров'),
        ),
    ]
