# Generated by Django 4.2 on 2023-06-06 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': 'Версия', 'verbose_name_plural': 'Версия'},
        ),
    ]
