# Generated by Django 4.2 on 2023-06-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_version_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название версии'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер версии'),
        ),
    ]
